-- ====================================================================
-- SUPABASE PRODUCTION-READY DATABASE SCHEMA & RLS POLICIES
-- Flipkart-Style Storefront & Admin Panel Catalog
-- ====================================================================

-- 1. Enable pgcrypto for UUID generation if not already enabled
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ====================================================================
-- 2. PRODUCTS TABLE
-- ====================================================================
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  md5_id text unique,
  name text not null,
  short_name text,
  brand text,
  category text default 'Kitchen',
  selling_price numeric not null default 0,
  mrp numeric not null default 0,
  deal_price numeric default 0,
  discount_percent integer default 0,
  discount_label text,
  rating text default '4.4',
  rating_stars numeric default 4.4,
  review_count text default '0',
  img1 text not null default '',
  images jsonb default '[]'::jsonb,
  features text,
  specs jsonb default '{}'::jsonb,
  badge text,
  delivery_text text,
  seller_name text,
  seller_rating text,
  ad boolean default false,
  authorized_seller boolean default true,
  assured boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ====================================================================
-- 2.1 ADMIN AUTHORIZATION TABLE
-- ====================================================================
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id)
  on delete cascade
);

-- Indexes for lightning-fast queries
create index if not exists idx_products_category on public.products(category);
create index if not exists idx_products_brand on public.products(brand);
create index if not exists idx_products_md5_id on public.products(md5_id);
create index if not exists idx_products_selling_price on public.products(selling_price);

-- Auto-update updated_at timestamp trigger
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language 'plpgsql';

drop trigger if exists trigger_products_updated_at on public.products;
create trigger trigger_products_updated_at
    before update on public.products
    for each row
    execute function update_updated_at_column();

-- ====================================================================
-- 3. ORDERS TABLE (Customer privacy protected)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id TEXT UNIQUE NOT NULL,
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    total_amount NUMERIC NOT NULL DEFAULT 0,
    mrp_amount NUMERIC DEFAULT 0,
    payment_method TEXT,
    address JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT DEFAULT 'Order Confirmed',
    expected_delivery TEXT DEFAULT 'Tomorrow by 11 PM',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_order_id ON public.orders(order_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);

-- ====================================================================
-- 4. SITE SETTINGS TABLE (Global banners, coupons, etc.)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.site_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ====================================================================
-- 5. ROW LEVEL SECURITY (RLS) POLICIES
-- ====================================================================

-- 5.1 Products Table Security
alter table public.products enable row level security;
alter table public.admin_users enable row level security;

-- Public read access: Anyone can browse the live products catalog
drop policy if exists "Public can read products" on public.products;
drop policy if exists "Public can view products" on public.products;
create policy "Public can read products"
on public.products
for select
to anon, authenticated
using (true);

-- Authenticated Admin only write access (Insert, Update, Delete) checked against admin_users table
drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products"
on public.products
for insert
to authenticated
with check (
  exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid())
  )
);

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products"
on public.products
for update
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid())
  )
);

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
on public.products
for delete
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid())
  )
);

-- 5.2 Orders Table Security
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Customers can place new orders (Insert)
DROP POLICY IF EXISTS "Public can create orders" ON public.orders;
CREATE POLICY "Public can create orders"
    ON public.orders
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

-- Customer privacy protection: Only authenticated admins can browse all orders
DROP POLICY IF EXISTS "Admins can view all orders" ON public.orders;
CREATE POLICY "Admins can view all orders"
    ON public.orders
    FOR SELECT
    TO authenticated
    USING (true);

DROP POLICY IF EXISTS "Admins can update orders" ON public.orders;
CREATE POLICY "Admins can update orders"
    ON public.orders
    FOR UPDATE
    TO authenticated
    USING (true);

-- 5.3 Site Settings Security
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read site settings" ON public.site_settings;
CREATE POLICY "Public can read site settings"
    ON public.site_settings
    FOR SELECT
    TO public
    USING (true);

DROP POLICY IF EXISTS "Admins can update site settings" ON public.site_settings;
CREATE POLICY "Admins can update site settings"
    ON public.site_settings
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- ====================================================================
-- 6. ENABLE SUPABASE REALTIME PUBLICATION ON PRODUCTS TABLE
-- Allows instant catalog sync across all browsers when admin edits
-- ====================================================================
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'products'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
    END IF;
END $$;
